import type { TemplateConfig } from '../types/templates';

export const arenaLive: TemplateConfig = {
  id: 'arenaLive',
  name: 'Arena Live',
  nameEn: 'Arena Live',
  description: 'สไตล์ถ่ายทอดสดมืออาชีพ',
  styleMode: '2d',
  layoutType: 'left-right',
  scorePosition: 'inner',
  logoPosition: 'left',
  colors: {
    teamABg: { type: 'solid', color: '#333333', alpha: 1 },
    teamBBg: { type: 'solid', color: '#333333', alpha: 1 },
    scoreABg: { type: 'solid', color: '#ffffff', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#ffffff', alpha: 1 },
    framePrimary: { type: 'solid', color: '#222222', alpha: 1 },
    frameInner: { type: 'solid', color: '#1a1a1a', alpha: 1 },
    highlight: { type: 'solid', color: '#cc0000', alpha: 1 },
    glow: { type: 'solid', color: '#cc0000', alpha: 0.5 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#cc0000', alpha: 1 },
    halfSlot: { type: 'solid', color: '#990000', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#ffffff', alpha: 1 },
  },
  style: {
    borderThickness: 3,
    cornerRadius: 0,
    bevelDepth: 2,
    shadowStrength: 0.55,
    highlightStrength: 0.8,
    glowStrength: 0.2,
    frameDepth: 2,
    skewX: 0,
    techBorders: false,
    patternStyle: 'none',
    moduleShape: 'rect',
  },
  dimensions: { width: 960, height: 64, spacing: 2 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
