import type { TemplateConfig } from '../types/templates';

export const flameSplit: TemplateConfig = {
  id: 'flameSplit',
  name: 'Flame Split',
  nameEn: 'Flame Split',
  description: 'สไตล์เปลวไฟและน้ำแข็ง',
  styleMode: '2d',
  layoutType: 'left-right',
  scorePosition: 'inner',
  logoPosition: 'center',
  colors: {
    teamABg: { type: 'linear', color: '#ff4500', alpha: 1, stops: [{offset: 0, color: '#ff4500'}, {offset: 1, color: '#8b0000'}] },
    teamBBg: { type: 'linear', color: '#00bfff', alpha: 1, stops: [{offset: 0, color: '#00bfff'}, {offset: 1, color: '#00008b'}] },
    scoreABg: { type: 'solid', color: '#ffffff', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#ffffff', alpha: 1 },
    framePrimary: { type: 'solid', color: '#000000', alpha: 1 },
    frameInner: { type: 'solid', color: '#111111', alpha: 1 },
    highlight: { type: 'solid', color: '#ffffff', alpha: 0.2 },
    glow: { type: 'solid', color: '#ffffff', alpha: 0 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#1a1a1a', alpha: 1 },
    halfSlot: { type: 'solid', color: '#000000', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#111111', alpha: 1 },
  },
  style: {
    borderThickness: 2,
    cornerRadius: 2,
    bevelDepth: 0,
    shadowStrength: 0.6,
    highlightStrength: 0.3,
    glowStrength: 0,
    frameDepth: 0,
    skewX: -0.1,
    techBorders: false,
    patternStyle: 'none',
    moduleShape: 'rect',
  },
  dimensions: { width: 900, height: 74, spacing: 4 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
