import type { TemplateConfig } from '../types/templates';

export const glassmorphism: TemplateConfig = {
  id: 'glassmorphism',
  name: 'Glassmorphism',
  nameEn: 'Glassmorphism',
  description: 'สไตล์โปร่งแสงทันสมัย',
  styleMode: '3d',
  layoutType: 'left-right',
  scorePosition: 'inner',
  logoPosition: 'center',
  colors: {
    teamABg: { type: 'solid', color: '#ffffff', alpha: 0.2 },
    teamBBg: { type: 'solid', color: '#ffffff', alpha: 0.2 },
    scoreABg: { type: 'solid', color: '#ffffff', alpha: 0.3 },
    scoreBBg: { type: 'solid', color: '#ffffff', alpha: 0.3 },
    framePrimary: { type: 'solid', color: '#ffffff', alpha: 0.15 },
    frameInner: { type: 'solid', color: '#ffffff', alpha: 0.1 },
    highlight: { type: 'solid', color: '#ffffff', alpha: 0.5 },
    glow: { type: 'solid', color: '#8a2be2', alpha: 0.8 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#ffffff', alpha: 0.25 },
    halfSlot: { type: 'solid', color: '#ffffff', alpha: 0.2 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#ffffff', alpha: 0.25 },
  },
  style: {
    borderThickness: 1,
    cornerRadius: 16,
    bevelDepth: 2,
    shadowStrength: 0.4,
    highlightStrength: 0.6,
    glowStrength: 0.8,
    frameDepth: 4,
    skewX: 0,
    techBorders: false,
    patternStyle: 'dots',
    moduleShape: 'pill',
  },
  dimensions: { width: 860, height: 78, spacing: 10 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
