import type { TemplateConfig } from '../types/templates';

export const goldCup: TemplateConfig = {
  id: 'goldCup',
  name: 'Gold Trophy Cup',
  nameEn: 'Gold Trophy Cup',
  description: 'สไตล์ถ้วยรางวัลสีทองหรูหรา',
  styleMode: '3d',
  layoutType: 'left-right',
  scorePosition: 'inner',
  logoPosition: 'center',
  colors: {
    teamABg: { type: 'solid', color: '#1a1a1a', alpha: 1 },
    teamBBg: { type: 'solid', color: '#1a1a1a', alpha: 1 },
    scoreABg: { type: 'linear', color: '#d4af37', alpha: 1, stops: [{offset: 0, color: '#f3e5ab'}, {offset: 1, color: '#aa7c11'}] },
    scoreBBg: { type: 'linear', color: '#d4af37', alpha: 1, stops: [{offset: 0, color: '#f3e5ab'}, {offset: 1, color: '#aa7c11'}] },
    framePrimary: { type: 'linear', color: '#d4af37', alpha: 1, stops: [{offset: 0, color: '#ffd700'}, {offset: 1, color: '#b8860b'}] },
    frameInner: { type: 'solid', color: '#000000', alpha: 1 },
    highlight: { type: 'solid', color: '#ffbf00', alpha: 0.5 },
    glow: { type: 'solid', color: '#d4af37', alpha: 0.6 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#222222', alpha: 1 },
    halfSlot: { type: 'solid', color: '#111111', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#000000', alpha: 1 },
  },
  style: {
    borderThickness: 2,
    cornerRadius: 6,
    bevelDepth: 10,
    shadowStrength: 0.9,
    highlightStrength: 0.8,
    glowStrength: 0.7,
    frameDepth: 16,
    skewX: 0,
    techBorders: false,
    patternStyle: 'none',
    moduleShape: 'rect',
  },
  dimensions: { width: 880, height: 76, spacing: 4 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
