import type { TemplateConfig } from '../types/templates';

export const mechSymmetry: TemplateConfig = {
  id: 'mechSymmetry',
  name: 'Mech Symmetry',
  nameEn: 'Mech Symmetry',
  description: 'ธีมล้ำยุค สไตล์ไซไฟ มีเส้นขอบแบบ Tech และกรอบโลโก้ทรงหกเหลี่ยม',
  layoutType: 'left-right',
  scorePosition: 'inner',
  logoPosition: 'center',
  styleMode: '3d',
  colors: {
    teamABg: { type: 'linear', color: '#1a1a1a', alpha: 1, stops: [{ offset: 0, color: '#1a1a1a' }, { offset: 1, color: '#0d0d0d' }] },
    teamBBg: { type: 'linear', color: '#1a1a1a', alpha: 1, stops: [{ offset: 0, color: '#1a1a1a' }, { offset: 1, color: '#0d0d0d' }] },
    scoreABg: { type: 'linear', color: '#2a0000', alpha: 1, stops: [{ offset: 0, color: '#2a0000' }, { offset: 1, color: '#140000' }] },
    scoreBBg: { type: 'linear', color: '#2a0000', alpha: 1, stops: [{ offset: 0, color: '#2a0000' }, { offset: 1, color: '#140000' }] },
    framePrimary: { type: 'linear', color: '#000000', alpha: 1, stops: [{ offset: 0, color: '#222222' }, { offset: 1, color: '#000000' }] },
    frameInner: { type: 'solid', color: '#333333', alpha: 1 },
    highlight: { type: 'solid', color: '#ff1e1e', alpha: 1 },
    glow: { type: 'solid', color: '#ff0000', alpha: 0.1 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.9 },
    timeSlot: { type: 'solid', color: '#000000', alpha: 0.8 },
    halfSlot: { type: 'solid', color: '#000000', alpha: 0.8 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'linear', color: '#000000', alpha: 1, stops: [{ offset: 0, color: '#333333' }, { offset: 1, color: '#111111' }] },
  },
  style: {
    cornerRadius: 4,
    borderThickness: 3,
    bevelDepth: 8,
    shadowStrength: 0.8,
    glowStrength: 0.3,
    highlightStrength: 1.0,
    frameDepth: 0,
    skewX: 0,
    techBorders: true,
    patternStyle: 'none',
    moduleShape: 'rect',
  },
  dimensions: {
    width: 950,
    height: 80,
    spacing: 8,
  },
  modulesEnabled: {
    time: true,
    half: true,
    yellowCardA: true,
    yellowCardB: true,
    redCardA: true,
    redCardB: true,
  }
};
