import type { TemplateConfig } from '../types/templates';

export const neonStrike: TemplateConfig = {
  id: 'neonStrike',
  name: 'Neon Strike',
  nameEn: 'Neon Strike',
  description: 'สไตล์อีสปอร์ตสีเขียวนีออน',
  styleMode: '3d',
  layoutType: 'left-right',
  scorePosition: 'outer',
  logoPosition: 'center',
  colors: {
    teamABg: { type: 'solid', color: '#0a0a0a', alpha: 1 },
    teamBBg: { type: 'solid', color: '#0a0a0a', alpha: 1 },
    scoreABg: { type: 'solid', color: '#111111', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#111111', alpha: 1 },
    framePrimary: { type: 'solid', color: '#00ff88', alpha: 1 },
    frameInner: { type: 'solid', color: '#000000', alpha: 1 },
    highlight: { type: 'solid', color: '#00ff88', alpha: 0.8 },
    glow: { type: 'solid', color: '#00ff88', alpha: 1 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#050505', alpha: 1 },
    halfSlot: { type: 'solid', color: '#050505', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#050505', alpha: 1 },
  },
  style: {
    borderThickness: 2,
    cornerRadius: 8,
    bevelDepth: 5,
    shadowStrength: 0.8,
    highlightStrength: 1,
    glowStrength: 1,
    frameDepth: 8,
    skewX: 0.05,
    techBorders: true,
    patternStyle: 'grid',
    moduleShape: 'pill',
  },
  dimensions: { width: 920, height: 72, spacing: 6 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
