import type { TemplateConfig } from '../types/templates';

export const ruggedMetal: TemplateConfig = {
  id: 'ruggedMetal',
  name: 'Rugged Metal',
  nameEn: 'Rugged Metal',
  description: 'สไตล์เหล็กหุ้มเกราะ',
  styleMode: '3d',
  layoutType: 'left-right',
  scorePosition: 'inner',
  logoPosition: 'center',
  colors: {
    teamABg: { type: 'solid', color: '#2c2f33', alpha: 1 },
    teamBBg: { type: 'solid', color: '#2c2f33', alpha: 1 },
    scoreABg: { type: 'solid', color: '#1a1a1a', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#1a1a1a', alpha: 1 },
    framePrimary: { type: 'solid', color: '#444444', alpha: 1 },
    frameInner: { type: 'solid', color: '#111111', alpha: 1 },
    highlight: { type: 'solid', color: '#ff6600', alpha: 0.8 },
    glow: { type: 'solid', color: '#ff6600', alpha: 0.6 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#222222', alpha: 1 },
    halfSlot: { type: 'solid', color: '#1a1a1a', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#333333', alpha: 1 },
  },
  style: {
    borderThickness: 4,
    cornerRadius: 2,
    bevelDepth: 18,
    shadowStrength: 1,
    highlightStrength: 0.9,
    glowStrength: 0.5,
    frameDepth: 20,
    skewX: 0,
    techBorders: true,
    patternStyle: 'grid',
    moduleShape: 'rect',
  },
  dimensions: { width: 940, height: 88, spacing: 6 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
