import type { TemplateConfig } from '../types/templates';

export const speedAsym: TemplateConfig = {
  id: 'speedAsym',
  name: 'Speed Asymmetric',
  nameEn: 'Speed Asym',
  description: 'ธีมโฉบเฉี่ยว เอียงแบบความเร็วสูง โลโก้อยู่ซ้ายสุด คะแนนเด่นชัด',
  layoutType: 'left-right',
  scorePosition: 'outer',
  logoPosition: 'left',
  styleMode: '2d',
  colors: {
    teamABg: { type: 'solid', color: '#111111', alpha: 1 },
    teamBBg: { type: 'solid', color: '#ffffff', alpha: 1 },
    scoreABg: { type: 'solid', color: '#e60000', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#e60000', alpha: 1 },
    framePrimary: { type: 'solid', color: '#000000', alpha: 0.9 },
    frameInner: { type: 'solid', color: '#222222', alpha: 1 },
    highlight: { type: 'solid', color: '#e60000', alpha: 1 },
    glow: { type: 'solid', color: '#e60000', alpha: 0.2 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.8 },
    timeSlot: { type: 'solid', color: '#000000', alpha: 1 },
    halfSlot: { type: 'solid', color: '#000000', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#000000', alpha: 1 },
  },
  style: {
    cornerRadius: 0,
    borderThickness: 0,
    bevelDepth: 0,
    shadowStrength: 1.0,
    glowStrength: 0,
    highlightStrength: 1.0,
    frameDepth: 0,
    skewX: -0.3,
    techBorders: false,
    patternStyle: 'none',
    moduleShape: 'rect',
  },
  dimensions: {
    width: 900,
    height: 70,
    spacing: 12,
  },
  modulesEnabled: {
    time: true,
    half: true,
    yellowCardA: true,
    yellowCardB: true,
    redCardA: true,
    redCardB: true,
  }
};
