import type { TemplateConfig } from '../types/templates';

export const splitArrow: TemplateConfig = {
  id: 'splitArrow',
  name: 'Split Arrow',
  nameEn: 'Split Arrow',
  description: 'สไตล์ลูกศรแหลมแยกฝั่ง',
  styleMode: '2d',
  layoutType: 'left-right',
  scorePosition: 'inner',
  logoPosition: 'center',
  colors: {
    teamABg: { type: 'solid', color: '#8b0000', alpha: 1 },
    teamBBg: { type: 'solid', color: '#00008b', alpha: 1 },
    scoreABg: { type: 'solid', color: '#ffffff', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#ffffff', alpha: 1 },
    framePrimary: { type: 'solid', color: '#111111', alpha: 1 },
    frameInner: { type: 'solid', color: '#222222', alpha: 1 },
    highlight: { type: 'solid', color: '#ffffff', alpha: 0.3 },
    glow: { type: 'solid', color: '#ffffff', alpha: 0 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#111111', alpha: 1 },
    halfSlot: { type: 'solid', color: '#000000', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#111111', alpha: 1 },
  },
  style: {
    borderThickness: 2,
    cornerRadius: 0,
    bevelDepth: 3,
    shadowStrength: 0.6,
    highlightStrength: 0.55,
    glowStrength: 0,
    frameDepth: 2,
    skewX: 0.06,
    techBorders: false,
    patternStyle: 'stripes',
    moduleShape: 'parallelogram',
  },
  dimensions: { width: 900, height: 68, spacing: 2 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
