import type { TemplateConfig } from '../types/templates';

export const techSlantLeft: TemplateConfig = {
  id: 'techSlantLeft',
  name: 'Tech Slant',
  nameEn: 'Tech Slant',
  description: 'เลย์เอาต์ทีมบน-ล่าง ขอบกรอบตัดเฉียง และกรอบโลโก้คางหมู',
  layoutType: 'top-bottom',
  scorePosition: 'after',
  logoPosition: 'left',
  styleMode: '3d',
  colors: {
    teamABg: { type: 'solid', color: '#ffffff', alpha: 0.9 },
    teamBBg: { type: 'solid', color: '#ffffff', alpha: 0.9 },
    scoreABg: { type: 'solid', color: '#e60000', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#000000', alpha: 1 },
    framePrimary: { type: 'solid', color: '#111111', alpha: 1 },
    frameInner: { type: 'solid', color: '#444444', alpha: 1 },
    highlight: { type: 'solid', color: '#ffffff', alpha: 0.8 },
    glow: { type: 'solid', color: '#e60000', alpha: 0.2 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.8 },
    timeSlot: { type: 'solid', color: '#e60000', alpha: 1 },
    halfSlot: { type: 'solid', color: '#000000', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#0a0a0a', alpha: 1 },
  },
  style: {
    cornerRadius: 0,
    borderThickness: 2,
    bevelDepth: 4,
    shadowStrength: 0.8,
    glowStrength: 0.4,
    highlightStrength: 0.9,
    frameDepth: 3,
    skewX: -0.04,
    techBorders: true,
    patternStyle: 'none',
    moduleShape: 'rect',
  },
  dimensions: {
    width: 360,
    height: 120,
    spacing: 4,
  },
  modulesEnabled: {
    time: true,
    half: true,
    yellowCardA: true,
    yellowCardB: true,
    redCardA: true,
    redCardB: true,
  }
};
