import type { TemplateConfig } from '../types/templates';

export const ultraWide: TemplateConfig = {
  id: 'ultraWide',
  name: 'Ultra Wide',
  nameEn: 'Ultra Wide',
  description: 'สไตล์จอกว้างระดับพรีเมียม',
  styleMode: '3d',
  layoutType: 'left-right',
  scorePosition: 'outer',
  logoPosition: 'center',
  colors: {
    teamABg: { type: 'solid', color: '#0a192f', alpha: 1 },
    teamBBg: { type: 'solid', color: '#0a192f', alpha: 1 },
    scoreABg: { type: 'solid', color: '#ffffff', alpha: 1 },
    scoreBBg: { type: 'solid', color: '#ffffff', alpha: 1 },
    framePrimary: { type: 'solid', color: '#c0c0c0', alpha: 1 },
    frameInner: { type: 'solid', color: '#e0e0e0', alpha: 1 },
    highlight: { type: 'solid', color: '#ffffff', alpha: 0.6 },
    glow: { type: 'solid', color: '#ffffff', alpha: 0.3 },
    shadow: { type: 'solid', color: '#000000', alpha: 0.85 },
    timeSlot: { type: 'solid', color: '#112240', alpha: 1 },
    halfSlot: { type: 'solid', color: '#0a192f', alpha: 1 },
    yellowCard: { type: 'solid', color: '#FFCD00', alpha: 1 },
    redCard: { type: 'solid', color: '#E8000D', alpha: 1 },
    logoPlateBg: { type: 'solid', color: '#c0c0c0', alpha: 1 },
  },
  style: {
    borderThickness: 3,
    cornerRadius: 4,
    bevelDepth: 8,
    shadowStrength: 0.7,
    highlightStrength: 0.8,
    glowStrength: 0.4,
    frameDepth: 10,
    skewX: 0,
    techBorders: false,
    patternStyle: 'none',
    moduleShape: 'rect',
  },
  dimensions: { width: 1200, height: 90, spacing: 8 },
  modulesEnabled: { time: true, half: true, yellowCardA: true, yellowCardB: true, redCardA: true, redCardB: true },
};
